[versions]
agp = "8.9.0"
kotlin = "2.1.10"
junit = "5.12.1"
coroutines = "1.10.1"
retrofit = "2.11.0"

[libraries]
junit = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

