package dev.olgiati.subsonik.model.nowPlaying

import dev.olgiati.subsonik.model.Child
import dev.olgiati.subsonik.model.artist.Contributor
import dev.olgiati.subsonik.model.ReplayGain
import dev.olgiati.subsonik.model.artist.ArtistsID3
import dev.olgiati.subsonik.model.genre.ItemGenre
import java.util.Date

class NowPlayingEntry(
    id: String,
    parent: String?,
    isDir: Boolean,
    title: String,
    album: String?,
    artist: String?,
    track: Int?,
    year: Int?,
    genre: String?,
    coverArt: String?,
    size: Long?,
    contentType: String?,
    suffix: String?,
    transcodedContentType: String?,
    transcodedSuffix: String?,
    duration: Int?,
    bitRate: Int?,
    bitDepth: Int?,
    samplingRate: Int?,
    channelCount: Int?,
    path: String?,
    isVideo: Boolean?,
    userRating: Int?,
    averageRating: Double?,
    playCount: Long?,
    discNumber: Int?,
    created: Date?,
    starred: Date?,
    albumId: String?,
    artistId: String?,
    type: String?,
    mediaType: String?,
    bookmarkPosition: Long?,
    originalWidth: Int?,
    originalHeight: Int?,
    played: Date?,
    bpm: Int?,
    comment: String?,
    sortName: String?,
    musicBrainzId: String?,
    genres: List<ItemGenre>?,
    artists: List<ArtistsID3>?,
    displayArtist: String?,
    albumArtists: List<ArtistsID3>?,
    displayAlbumArtist: String?,
    contributors: List<Contributor>,
    displayComposer: String?,
    moods: List<String>?,
    replayGain: ReplayGain?,
    explicitStatus: String?,
    val username: String,
    val minuetsAgo: String,
    val playerId: String,
    val playerName: String?,
) : Child(
    id,
    parent,
    isDir,
    title,
    album,
    artist,
    track,
    year,
    genre,
    coverArt,
    size,
    contentType,
    suffix,
    transcodedContentType,
    transcodedSuffix,
    duration,
    bitRate,
    bitDepth,
    samplingRate,
    channelCount,
    path,
    isVideo,
    userRating,
    averageRating,
    playCount,
    discNumber,
    created,
    starred,
    albumId,
    artistId,
    type,
    mediaType,
    bookmarkPosition,
    originalWidth,
    originalHeight,
    played,
    bpm,
    comment,
    sortName,
    musicBrainzId,
    genres,
    artists,
    displayArtist,
    albumArtists,
    displayAlbumArtist,
    contributors,
    displayComposer,
    moods,
    replayGain,
    explicitStatus,
)
