package dev.olgiati.subsonik.model

import dev.olgiati.subsonik.model.artist.ArtistsID3
import dev.olgiati.subsonik.model.artist.Contributor
import dev.olgiati.subsonik.model.genre.ItemGenre
import java.util.Date

open class Child(
    val id: String,
    val parent: String?,
    val isDir: Boolean,
    val title: String,
    val album: String?,
    val artist: String?,
    val track: Int?,
    val year: Int?,
    val genre: String?,
    val coverArt: String?,
    val size: Long?,
    val contentType: String?,
    val suffix: String?,
    val transcodedContentType: String?,
    val transcodedSuffix: String?,
    val duration: Int?,
    val bitRate: Int?,
    val bitDepth: Int?,
    val samplingRate: Int?,
    val channelCount: Int?,
    val path: String?,
    val isVideo: Boolean?,
    val userRating: Int?,
    val averageRating: Double?,
    val playCount: Long?,
    val discNumber: Int?,
    val created: Date?,
    val starred: Date?,
    val albumId: String?,
    val artistId: String?,
    val type: String?,
    val mediaType: String?,
    val bookmarkPosition: Long?,
    val originalWidth: Int?,
    val originalHeight: Int?,
    val played: Date?,
    val bpm: Int?,
    val comment: String?,
    val sortName: String?,
    val musicBrainzId: String?,
    val genres: List<ItemGenre>?,
    val artists: List<ArtistsID3>?,
    val displayArtist: String?,
    val albumArtists: List<ArtistsID3>?,
    val displayAlbumArtist: String?,
    val contributors: List<Contributor>,
    val displayComposer: String?,
    val moods: List<String>?,
    val replayGain: ReplayGain?,
    val explicitStatus: String?,
)